
## flowchart

flowchart LR
%% Abstract
classDef api fill:#f9f,stroke:#333,stroke-width:1px;
classDef core fill:#9ff,stroke:#333,stroke-width:1px;
classDef intg fill:#ff9,stroke:#333,stroke-width:1px;

%% API Layer Nodes
API[api.py]:::api
DEC[decorators.py]:::api

%% Core Nodes
CPU[core/cpu/compute.*]:::core
IO[core/io/io_utils.py]:::core
PAR_P[core/parallel/process_pool.py]:::core
PAR_T[core/parallel/thread_pool.py]:::core
Q[core/queue.py]:::core
CONN[core/connection.py]:::core
PR[core/process.py]:::core
FORK[core/forking.py]:::core
RED[core/reduction.py]:::core
MEM[core/shared_memory.py]:::core
SYNC[core/sync.py]:::core
MAN[core/managers.py]:::core

%% Integration Nodes
NP[integration/numpy_integration.py]:::intg
PD[integration/pandas_integration.py]:::intg
SK[integration/sklearn_integration.py]:::intg

%% Core Connection With API
API --> DEC  
 DEC --> CPU
DEC --> IO
DEC --> PAR_P
DEC --> PAR_T
API --> PAR_P
API --> PAR_T
API --> Q
API --> CONN
API --> MEM
API --> SYNC

%% Internal Connection Core
PAR_P --> CPU
PAR_P --> IO
PAR_P --> MEM
PAR_P --> SYNC
PAR_T --> IO
Q --> CONN
MAN --> CONN
MAN --> RED
PR --> FORK
PR --> RED
PR --> MAN
RED --> CONN
RED --> MEM
SYNC --> MEM

%% Connection Integration
NP --> CPU
PD --> PAR_P
PD --> IO
SK --> CPU
SK --> PAR_P
