---
config:
  layout: fixed
---
flowchart LR
    API["api.py"] --> DEC["decorators.py"] & PAR_P["core/parallel/process_pool.py"] & PAR_T["core/parallel/thread_pool.py"] & Q["core/queue.py"] & CONN["core/connection.py"] & MEM["core/shared_memory.py"] & SYNC["core/sync.py"]
    DEC --> CPU["core/cpu/compute.*"] & IO["core/io/io_utils.py"] & PAR_P & PAR_T
    PAR_P --> CPU & IO & MEM & SYNC
    PAR_T --> IO
    Q --> CONN
    MAN["core/managers.py"] --> CONN & RED["core/reduction.py"]
    PR["core/process.py"] --> FORK["core/forking.py"] & RED & MAN
    RED --> CONN & MEM
    SYNC --> MEM
    NP["integration/numpy_integration.py"] --> CPU
    PD["integration/pandas_integration.py"] --> PAR_P & IO
    SK["integration/sklearn_integration.py"] --> CPU & PAR_P
     API:::api
     DEC:::api
     CPU:::core
     IO:::core
     PAR_P:::core
     PAR_T:::core
     Q:::core
     CONN:::core
     PR:::core
     FORK:::core
     RED:::core
     MEM:::core
     SYNC:::core
     MAN:::core
     NP:::intg
     PD:::intg
     SK:::intg
    classDef api fill:#f9f,stroke:#333,stroke-width:1px
    classDef core fill:#9ff,stroke:#333,stroke-width:1px
    classDef intg fill:#ff9,stroke:#333,stroke-width:1px
